name: Publish

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  fake-publish-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: echo " ##### publish ######"
        if: steps.check.outputs.triggered == 'true'
