name: PR Publish

on:
  issue_comment:
    types: [created, edited]

jobs:
  pr-comment-jobs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: |
          echo "display some env var"
          echo "pull request " ${{ github.event.issue.pull_request }}
          echo "github.event.comment.body" ${{ github.event.comment.body }}
      - run: echo __publish__
        if: ${{ github.event.issue.pull_request && github.event.comment.body  == '/publish' }}
        name: fake-publish
